#!/usr/bin/env bash
# This script displays information about users from /etc/passwd using a while loop and IFS.

while IFS=: read -r username _ uid gid info home shell; do
    echo "The user $username is a member of the $gid gang, residing in $home, and using $shell as the default shell."
    echo "The security of user $uid's account is safeguarded by the passcode $info. Additional user details: $uid INFO"
done < /etc/passwd

