#!/usr/bin/env bash
# This script displays information about users from /etc/passwd using a while loop and IFS.

while IFS=: read -r username _ uid gid info home shell; do
    printf "The user %s is part of the %s gang, lives in %s, and rides %s.\n" "$username" "$gid" "$home" "$shell"
    printf "USER ID's place is protected by the passcode %s, more info about the user here: %s INFO\n" "$info" "$uid"
done < /etc/passwd


